@startuml
'https://plantuml.com/class-diagram

interface A
class B
class C
interface D
interface E

interface A{
    void m1();
    void m2();
    void m3();
}
class B implements A{
    void m1();
    void m2();
}
class C implements A{
    void m1();
}
interface D extends A{
    void m2();
}
interface E extends A{
    void m1();
    void m2();
    void m3();
}




@enduml
